---
- name: Install nginx
  apt:
    name: nginx
    state: present
    
- name: Put nginx configuration file
  template:
    src: default
    dest: /etc/nginx/sites-available/default
    
- name: Enable nginx service
  service:
    name: nginx
    enabled: yes
    state: restarted