- hosts: all
  gather_facts: False
  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- hosts: lb
  become: yes
  become_user: root
  roles:
    - nginx
  
- hosts: nodes
  become: yes
  become_user: root
  roles:
    - docker
    - app
