- name: Check if we are installing fresh Wordpress
  stat:
    path: /var/www/html/wp-login.php
  register: wp_present


- block:
  - name: Install unzip
    apt:
      name: unzip
      state: present

  - name: Unpack newest Wordpress distribution
    unarchive:
      src: https://wordpress.org/latest.zip
      remote_src: yes
      dest: /var/www
      owner: www-data

  - name: Remove the previous contents of html directory
    file:
      path: /var/www/html
      state: absent

  - name: Set Wordpress files folder as the root of the website
    command: 'mv /var/www/wordpress /var/www/html'

  when: wp_present.stat.exists == False

- name: Put wp-config.php configuration file
  template:
    src: wp-config.php
    dest: /var/www/html/

